---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'one-ring'
SiteConfig:
  extensions:
    - SiteConfigExtension
---
Only:
  enviroment: dev
---
Email:
  send_all_emails_to: 'me@example.com'
---
Except:
  enviroment: dev
---
Email:
  bcc_all_emails_to: 'me@example.com'
